# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :validate do
    validate_play_store_json_key(
      json_key: 'C:\Projects\React_Native\noirly-messenger\chat-app-e1129-6d25afb3ce3c.json'
    )
  end

  lane :clean do
    gradle(
      task: 'clean'
    )
  end

  lane :internal do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
  end
end
