name: Download Google Services JSON

on:
  workflow_dispatch

jobs:
  create-google-services:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create google-services.json from secret
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "$GOOGLE_SERVICES_JSON" > google-services.json

      - name: Upload google-services.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: google-services-json
          path: google-services.json
          retention-days: 1